name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      platform:
        description: 'Select platform to build'
        required: true
        type: choice
        options:
          - all
          - mac
          - windows
        default: 'all'

jobs:
  build-mac:
    if: github.event_name == 'push' || github.event.inputs.platform == 'all' || github.event.inputs.platform == 'mac'
    uses: ./.github/workflows/build_mac.yml
    secrets: inherit

  build-windows:
    if: github.event_name == 'push' || github.event.inputs.platform == 'all' || github.event.inputs.platform == 'windows'
    uses: ./.github/workflows/build_windows.yml
    secrets: inherit
